# Generated by Django 2.0.4 on 2018-04-04 20:47

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('enrollment', models.CharField(default=users.models.generate_enrollment, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('cpf', models.IntegerField()),
                ('RG', models.IntegerField()),
                ('date_birth', models.DateField()),
                ('number', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
