# Generated by Django 2.0.4 on 2018-04-19 02:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('defaultuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.DefaultUser')),
                ('couse', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Curso')),
                ('semester', models.CharField(max_length=20, verbose_name='Semestre')),
                ('entrance_date', models.DateField(verbose_name='Data de Ingresso no Projeto')),
                ('college_enrollment', models.CharField(max_length=10, verbose_name='Matricula')),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
            },
            bases=('users.defaultuser',),
            managers=[
                ('objects', users.models.AccountManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='defaultuser',
            options={'verbose_name': 'Usuário Base', 'verbose_name_plural': 'Usuários Base'},
        ),
    ]
