# Generated by Django 2.0.4 on 2018-04-06 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_coisas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.DeleteModel(
            name='Coisas',
        ),
    ]
