# Generated by Django 2.0.4 on 2018-04-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='./images/default.svg', upload_to='./images/'),
        ),
    ]
