# Generated by Django 2.0.4 on 2018-04-19 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180419_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='couse',
            new_name='course',
        ),
    ]
