# Generated by Django 2.0.4 on 2018-05-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180510_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_member',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
