# Generated by Django 2.0.4 on 2018-04-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180419_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='course',
            field=models.CharField(max_length=20, verbose_name='Curso'),
        ),
    ]
