# Generated by Django 2.0.4 on 2018-04-06 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180406_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='number',
            new_name='phone_number',
        ),
    ]
