# Generated by Django 2.0.4 on 2018-04-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180419_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='picture',
            field=models.ImageField(default='images/users/default.png', upload_to='images/users/', verbose_name='Foto de Perfil'),
        ),
    ]
