# Generated by Django 2.0.4 on 2018-04-06 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180406_0053'),
        ('users', '0003_auto_20180406_0042'),
    ]

    operations = [
    ]
