# Generated by Django 2.0.4 on 2018-04-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20180406_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='images/default.svg', upload_to='images/'),
        ),
    ]
