# Generated by Django 2.0.4 on 2018-04-14 14:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_auto_20180406_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('enrollment', models.CharField(default=users.models.generate_enrollment, max_length=10, primary_key=True, serialize=False, verbose_name='Matrícula')),
                ('cpf', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
                ('rg', models.CharField(max_length=20)),
                ('date_birth', models.DateField()),
                ('phone_number', models.IntegerField()),
                ('picture', models.ImageField(default='images/default.svg', upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
