# Generated by Django 2.0.4 on 2018-04-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180414_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
