# Generated by Django 2.0.4 on 2018-04-14 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180414_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('userdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.UserData')),
                ('parentName', models.CharField(max_length=30)),
            ],
            bases=('users.userdata',),
        ),
    ]
