version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: cascata-db
  web:
    dns: 8.8.8.8
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db


