# Generated by Django 2.0.4 on 2018-05-10 23:28

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', tinymce.models.HTMLField(verbose_name='Body')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
