# Generated by Django 2.0.4 on 2018-04-24 14:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='Body'),
        ),
    ]
