# Generated by Django 2.0.4 on 2018-05-10 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Member'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='visible_to',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
